import { MenuItem } from "./menu.model";

export const MENU: any[] = [
  {
    id: 1,
    label: "Dashboards",
    isTitle: true,
  },
  {
    id: 2,
    label: "Home",
    permission: "Home",
    checkable: "module",
    icon: "bx bx-home-circle",
    link: "/home",
  },
  {
    id: 194,
    label: "HR Administration",
    permission: "corporate",
    checkable: "module",
    icon: "bx bxs-bar-chart-alt-2",
    subItems: [
      {
        id: 196,
        label: "Dashboard",
        permission: "hr_d",
        checkable: "permissions",
        link: "/hr-administration/dashboard",
        parentId: 194,
      },
      {
        id: 197,
        label: "Attendance",
        permission: "v_c_att",
        checkable: "permissions",
        link: "/hr-administration/attendance",
        parentId: 194,
      },
      {
        id: 198,
        label: "Regularization",
        permission: "v_c_reg",
        checkable: "permissions",
        link: "/hr-administration/regularization",
        parentId: 194,
      },
      {
        id: 199,
        label: "OD",
        permission: "v_c_odd",
        checkable: "permissions",
        link: "/hr-administration/OD",
        parentId: 194,
      },
      {
        id: 200,
        label: "Leave",
        permission: "v_c_leave",
        checkable: "permissions",
        link: "/hr-administration/leave",
        parentId: 194,
      },
      {
        id: 201,
        label: "FR Status",
        permission: "v_c_fr",
        checkable: "permissions",
        link: "/hr-administration/fr-status",
        parentId: 194,
      },
      {
        id: 202,
        label: "QR Tracker",
        permission: "v_c_qr",
        checkable: "permissions",
        link: "/hr-administration/qr-tracker",
        parentId: 194,
      },
      {
        id: 203,
        label: "Employee",
        permission: "v_c_emp",
        checkable: "permissions",
        link: "/hr-administration/employee",
        parentId: 194,
      },
      {
        id: 204,
        label: "Reports",
        permission: "v_c_rep",
        checkable: "permissions",
        link: "/hr-administration/reports",
        parentId: 194,
      },
    ],
  },
  {
    id: 3,
    label: "Main Dashboard",
    icon: "far fa-chart-bar",
    permission: "main_dashboard",
    checkable: "module",
    link: "/Dashboard",
  },
  {
    id: 4,
    permission: "Dashboard",
    checkable: "module",
    label: "Reports Dashboard",
    icon: "bx bxs-dashboard",
    subItems: [
      {
        id: 5,
        label: "HR Dashboard",
        permission: "hr_d",
        checkable: "permissions",
        link: "/hrdashoard",
        parentId: 4,
      },
      {
        id: 6,
        label: "Shortage Report",
        permission: "st_r",
        checkable: "permissions",
        link: "/shortage-report",
        parentId: 4,
      },
      {
        id: 7,
        label: "Help Desk",
        permission: "st_r",
        checkable: "permissions",
        link: "/help-desk",
        parentId: 4,
      },
    ],
  },
  {
    id: 8,
    label: "Apps",
    isTitle: true,
  },
  {
    id: 9,
    label: "Attendance",
    permission: "attendance",
    checkable: "module",
    icon: "bx bx-task",
    subItems: [
      {
        id: 10,
        label: "Attendance Logs",
        permission: "view_attendance_log",
        checkable: "permissions",
        link: "/attendance/attendance-log",
        parentId: 9,
      },
      {
        id: 193,
        label: "OD",
        permission: "v_od",
        checkable: "permissions",
        link: "/attendance/OD",
        parentId: 9,
      },
      {
        id: 11,
        label: "Manual Attendance",
        permission: "ma_v",
        checkable: "permissions",
        link: "/attendance/manual-attendance",
        parentId: 9,
      },
      {
        id: 12,
        label: "Regularizations",
        permission: "view_regularization_request",
        checkable: "permissions",
        link: "/attendance/attendance-approvals",
        parentId: 9,
      },
      {
        id: 13,
        label: "Patrol",
        permission: "view_patrol_list",
        checkable: "permissions",
        link: "/attendance/patrol",
        parentId: 9,
      },

      {
        id: 18,
        label: "Reports",
        permission: "v_reports",
        checkable: "permissions",
        link: "/attendance/reports",
        parentId: 9,
      },
      {
        id: 183,
        label: "PD Line",
        permission: "pdl_v",
        checkable: "permissions",
        link: "/attendance/pd-line",
        parentId: 9,
      },
    ],
  },
  {
    id: 19,
    label: "Applicant",
    permission: "applicant",
    checkable: "module",
    icon: "bx bxs-user",
    subItems: [
      {
        id: 20,
        label: "Dashboard",
        permission: "view_applicant_dashboard",
        checkable: "permissions",
        link: "/applicant/dashboard",
        parentId: 19,
      },
      {
        id: 21,
        label: "Invitations",
        permission: "view_invitation_list",
        checkable: "permissions",
        link: "/applicant/invitations",
        parentId: 19,
      },
    ],
  },
  {
    id: 22,
    label: "CRM",
    permission: "crm",
    checkable: "module",
    icon: "fas fa-handshake",
    subItems: [
      {
        id: 23,
        label: "Dashboard",
        permission: "v_crm_dash",
        checkable: "permissions",
        link: "/CRM/crm-dashboard",
        parentId: 22,
      },
      {
        id: 24,
        label: "CRM",
        permission: "v_crm",
        checkable: "permissions",
        link: "/CRM/dashboard",
        parentId: 22,
      },
      {
        id: 25,
        label: "Reports",
        permission: "v_rpt",
        checkable: "permissions",
        link: "/CRM/report",
        parentId: 22,
      },
      {
        id: 191,
        label: "Invitations",
        permission: "v_invt",
        checkable: "permissions",
        link: "/CRM/invitations",
        parentId: 22,
      },
      {
        id: 192,
        label: "My Activities",
        permission: "v_m_act",
        checkable: "permissions",
        link: "/CRM/todo-list",
        parentId: 22,
      },
      {
        id: 195,
        label: "CRM MIS",
        permission: "v_mis",
        checkable: "permissions",
        link: "/CRM/mis",
        parentId: 22,
      },
    ],
  },
  {
    id: 26,
    label: "Compliance",
    permission: "Compliance",
    checkable: "module",
    icon: "fas fa-gavel",
    link: "/compliance",
  },
  {
    id: 27,
    label: "Contract Management",
    permission: "contract_management",
    checkable: "module",
    icon: "fas fa-file-contract",
    link: "/contract",
  },
  {
    id: 28,
    label: "Employee Help Desk",
    permission: "employee_grievance",
    checkable: "module",
    icon: "bx bxs-help-circle",
    subItems: [
      {
        id: 29,
        label: "Grievance Dashboard",
        permission: "grievance_dashboard",
        checkable: "permissions",
        link: "/employee-help-desk/dashboard",
        parentId: 28,
      },
      {
        id: 30,
        label: "Grievance",
        permission: "grievance_list",
        checkable: "permissions",
        link: "/employee-help-desk/employee",
        parentId: 28,
      },
      {
        id: 30,
        label: "Posh Dashboard",
        permission: "posh_dashboard",
        checkable: "permissions",
        link: "/employee-help-desk/posh-dashboard",
        parentId: 28,
      },
      {
        id: 31,
        label: "Posh",
        permission: "posh_list",
        checkable: "permissions",
        link: "/employee-help-desk/posh",
        parentId: 28,
      },
      {
        id: 32,
        label: "Reports",
        permission: "show",
        checkable: "permissions",
        link: "/employee-help-desk/grievance-report/",
        parentId: 28,
      },
      {
        id: 33,
        label: "Work Flow",
        permission: "swf",
        checkable: "permissions",
        link: "/employee-help-desk/work-flow",
        parentId: 28,
      },
      {
        id: 34,
        label: "Helpdesk At Site",
        permission: "shdsk",
        checkable: "permissions",
        link: "/employee-help-desk/helpdesk-at-site",
        parentId: 28,
      },
    ],
  },
  {
    id: 35,
    label: "Green Checklist",
    permission: "green_checklist",
    checkable: "module",
    icon: "fas fa-door-open",
    subItems: [
      {
        id: 36,
        label: "Dashboard",
        permission: "v_gc",
        checkable: "permissions",
        link: "/green-checklist/dashboard",
        parentId: 35,
      },
      {
        id: 37,
        label: "Green Checklist",
        permission: "v_gc",
        checkable: "permissions",
        link: "/green-checklist/checklist",
        parentId: 35,
      },
      {
        id: 38,
        label: "Equipment Checklist",
        permission: "v_ec",
        checkable: "permissions",
        link: "/green-checklist/electric-checklist",
        parentId: 35,
      },
      {
        id: 39,
        label: "Reports",
        permission: "v_gcr",
        checkable: "permissions",
        link: "/green-checklist/reports",
        parentId: 35,
      },
    ],
  },
  {
    id: 40,
    label: "Incidents",
    permission: "incident",
    checkable: "module",
    icon: "fas fa-fire-extinguisher",
    subItems: [
      {
        id: 41,
        label: "Dashboard",
        permission: "v_inct_dash",
        checkable: "permissions",
        link: "/incident/dashboard",
        parentId: 40,
      },
      {
        id: 42,
        label: "Incidents",
        permission: "v_inct",
        checkable: "permissions",
        link: "/incident/incidents",
        parentId: 40,
      },
      {
        id: 43,
        label: "Rate Card",
        permission: "v_rc",
        checkable: "permissions",
        link: "/incident/rate-card",
        parentId: 40,
      },
      {
        id: 44,
        label: "Inventory",
        permission: "v_i_invt",
        checkable: "permissions",
        link: "/incident/incident-inventory",
        parentId: 40,
      },
    ],
  },
  {
    id: 45,
    label: "Inventory",
    permission: "inventory",
    checkable: "module",
    icon: "bx bx-search-alt",
    subItems: [
      {
        id: 46,
        label: "Inventory",
        permission: "v_invt",
        checkable: "permissions",
        link: "/inventory/inventory-item",
        parentId: 45,
      },
      {
        id: 47,
        label: "Category",
        permission: "v_cat",
        checkable: "permissions",
        link: "/inventory/inventory-category",
        parentId: 45,
      },
      {
        id: 48,
        label: "Type",
        permission: "v_tp",
        checkable: "permissions",
        link: "/inventory/inventory-type",
        parentId: 45,
      },
      {
        id: 49,
        label: "Item",
        permission: "v_itm",
        checkable: "permissions",
        link: "/inventory/inventories",
        parentId: 45,
      },
      {
        id: 187,
        label: "Reports",
        permission: "v_i_rpt",
        checkable: "permissions",
        link: "/inventory/reports",
        parentId: 45,
      },
    ],
  },
  {
    id: 50,
    label: "Legal Tracker",
    permission: "legal_tracker",
    checkable: "module",
    icon: "far fa-compass",
    subItems: [
      {
        id: 51,
        label: "Dashboard",
        permission: "lt_dashboard",
        checkable: "permissions",
        link: "/legal-tracker/dashboard",
        parentId: 50,
      },
      {
        id: 52,
        label: "Case Master",
        permission: "v_case_master",
        checkable: "permissions",
        link: "/legal-tracker/case-master",
        parentId: 50,
      },
      {
        id: 53,
        label: "Act",
        permission: "v_act",
        checkable: "permissions",
        link: "/legal-tracker/act",
        parentId: 50,
      },
      {
        id: 54,
        label: "Representative",
        permission: "v_representative",
        checkable: "permissions",
        link: "/legal-tracker/representative",
        parentId: 50,
      },
      {
        id: 55,
        label: "Authority",
        permission: "v_authority",
        checkable: "permissions",
        link: "/legal-tracker/authority",
        parentId: 50,
      },
      {
        id: 56,
        label: "Case Details",
        permission: "v_case_details",
        checkable: "permissions",
        link: "/legal-tracker/case-details",
        parentId: 50,
      },
      {
        id: 57,
        label: "Case Client Gratuity",
        permission: "v_ccg",
        checkable: "permissions",
        link: "/legal-tracker/case-client-gratuity",
        parentId: 50,
      },
      {
        id: 58,
        label: "Proceedings",
        permission: "v_proceeding",
        checkable: "permissions",
        link: "/legal-tracker/Proceedings",
        parentId: 50,
      },
      {
        id: 59,
        label: "Respondent",
        permission: "v_respondent",
        checkable: "permissions",
        link: "/legal-tracker/respondent",
        parentId: 50,
      },
      {
        id: 60,
        label: "Reports",
        permission: "l_report",
        checkable: "permissions",
        link: "/legal-tracker/reports",
        parentId: 50,
      },
    ],
  },
  {
    id: 89,
    label: "Me",
    permission: "me",
    checkable: "module",
    icon: "bx bx-user",
    subItems: [
      {
        id: 90,
        label: "Leave",
        link: "/me/summary",
        permission: "",
        checkable: "permissions",
        parentId: 89,
      },
      {
        id: 91,
        label: "Timesheet",
        permission: "",
        checkable: "permissions",
        subItems: [
          {
            id: 92,
            label: "All Timesheet",
            link: "/me/timesheet/timesheets-all",
            permission: "",
            checkable: "permissions",
            parentId: 91,
          },
          {
            id: 93,
            label: "Past Due",
            link: "/me/timesheet/past-due",
            permission: "",
            checkable: "permissions",
            parentId: 91,
          },
          {
            id: 94,
            label: "Rejected Timesheets",
            link: "/me/timesheet/rejected-timesheets",
            permission: "",
            checkable: "permissions",
            parentId: 91,
          },
          {
            id: 95,
            label: "Project Time",
            link: "/me/timesheet/project-time",
            permission: "",
            checkable: "permissions",
            parentId: 91,
          },
          {
            id: 96,
            label: "Week Summary",
            link: "/me/timesheet/week-summary",
            permission: "",
            checkable: "permissions",
            parentId: 91,
          },
        ],
        parentId: 89,
      },
      {
        id: 97,
        label: "Attendance",
        link: "/me/attendance/attendance-log",
        permission: "",
        checkable: "permissions",
        parentId: 89,
      },
      {
        id: 98,
        label: "Expenses & Travel",
        permission: "",
        checkable: "permissions",
        subItems: [
          {
            id: 99,
            label: "Pending Expenses",
            link: "/me/expensesandtravel/pending-expenses",
            permission: "",
            checkable: "permissions",
            parentId: 99,
          },
          {
            id: 100,
            label: "Past Claims",
            link: "/me/expensesandtravel/past-claims",
            permission: "",
            checkable: "permissions",
            parentId: 99,
          },
          {
            id: 101,
            label: "Advance Requests",
            link: "/me/expensesandtravel/advance-requests",
            permission: "",
            checkable: "permissions",
            parentId: 99,
          },
        ],
        parentId: 89,
      },
      {
        id: 102,
        label: "Helpdesk",
        permission: "",
        checkable: "permissions",
        subItems: [
          {
            id: 103,
            label: "My Tickets",
            link: "/me/helpdesk/my-tickets",
            permission: "",
            checkable: "permissions",
            parentId: 102,
          },
          {
            id: 104,
            label: "Following",
            link: "/me/helpdesk/tickets-following",
            permission: "",
            checkable: "permissions",
            parentId: 102,
          },
        ],
        parentId: 89,
      },
      {
        id: 105,
        label: "Billing",
        link: "/me/billing",
        permission: "",
        checkable: "permissions",
        parentId: 89,
      },
      {
        id: 106,
        label: "Client",
        link: "/me/client",
        permission: "",
        checkable: "permissions",
        parentId: 89,
      },
    ],
  },
  {
    id: 107,
    label: "My Team",
    permission: "my_team",
    checkable: "module",
    icon: "fas fa-user-friends",
    subItems: [
      {
        id: 108,
        label: "Summary",
        checkable: "permissions",
        permission: "",
        subItems: [
          {
            id: 109,
            label: "Direct Reports",
            link: "/my-team/summary/direct",
            checkable: "permissions",
            permission: "",
            parentId: 108,
          },
          {
            id: 110,
            label: "Peers",
            link: "/my-team/summary/peer",
            checkable: "permissions",
            permission: "",
            parentId: 108,
          },
        ],
        parentId: 107,
      },
      {
        id: 111,
        label: "Leave",
        checkable: "permissions",
        permission: "",
        subItems: [
          {
            id: 112,
            label: "Leave Overview",
            link: "/my-team/leave/leave-overview",
            checkable: "permissions",
            permission: "",
            parentId: 111,
          },
          {
            id: 113,
            label: "Leave Approvals",
            link: "my-team/leave/leave-approvals",
            checkable: "permissions",
            permission: "",
            parentId: 111,
          },
          {
            id: 114,
            label: "Penalized Leave",
            link: "my-team/leave/penalized-leave",
            checkable: "permissions",
            permission: "",
            parentId: 111,
          },
          {
            id: 115,
            label: "Past Leave Requests",
            link: "my-team/leave/past-leave-requests",
            checkable: "permissions",
            permission: "",
            parentId: 111,
          },
          {
            id: 116,
            label: "Reports",
            link: "my-team/leave/reports",
            checkable: "permissions",
            permission: "",
            parentId: 111,
          },
        ],
        parentId: 107,
      },
      {
        id: 117,
        label: "Expenses & Travel",
        checkable: "permissions",
        permission: "",
        subItems: [
          {
            id: 118,
            label: "Waiting For Approval",
            link: "/my-team/expenses-travel/waiting-for-approval",
            checkable: "permissions",
            permission: "",
            parentId: 117,
          },
          {
            id: 119,
            label: "Approved Claims",
            link: "/my-team/expenses-travel/approved-claims",
            checkable: "permissions",
            permission: "",
            parentId: 117,
          },
          {
            id: 120,
            label: "Past Claims",
            link: "/my-team/expenses-travel/past-claims",
            checkable: "permissions",
            permission: "",
            parentId: 117,
          },
        ],
        parentId: 107,
      },
      {
        id: 121,
        label: "Timesheet",
        checkable: "permissions",
        permission: "",
        subItems: [
          {
            id: 122,
            label: "Approvals",
            link: "/my-team/timesheet/timesheetapprovals",
            checkable: "permissions",
            permission: "",
            parentId: 121,
          },
          {
            id: 123,
            label: "Project Time",
            link: "/my-team/timesheet/projecttime",
            checkable: "permissions",
            permission: "",
            parentId: 121,
          },
          {
            id: 124,
            label: "Week Summary",
            link: "/my-team/timesheet/weeklysummary",
            checkable: "permissions",
            permission: "",
            parentId: 121,
          },
        ],
        parentId: 107,
      },
      {
        id: 125,
        label: "Profile Approvals",
        checkable: "permissions",
        permission: "",
        subItems: [
          {
            id: 126,
            label: "Pending Approval",
            link: "/my-team/profile-approvals/pending-approval",
            checkable: "permissions",
            permission: "",
            parentId: 125,
          },
          {
            id: 127,
            label: "Approved Changes",
            link: "/my-team/profile-approvals/approved-changes",
            checkable: "permissions",
            permission: "",
            parentId: 125,
          },
        ],
        parentId: 107,
      },
    ],
  },
  {
    id: 70,
    label: "ORG",
    permission: "organization",
    checkable: "module",
    icon: "fab fa-elementor",
    subItems: [
      {
        id: 71,
        label: "Dashboard",
        permission: "v_o_dash",
        checkable: "permissions",
        link: "/org/dashboard",
        parentId: 70,
      },
      {
        id: 72,
        label: "Analytics",
        permission: "v_alts",
        checkable: "permissions",
        link: "/org/analytics/hiring/details",
        parentId: 70,
      },
      {
        id: 73,
        label: "Employees",
        permission: "v_emps",
        checkable: "permissions",
        subItems: [
          {
            id: 731,
            label: "Employee Directory",
            link: "/org/employees/employee-directory/about/summary",
            permission: "",
            checkable: "permissions",
            parentId: 73,
          },
          {
            id: 732,
            label: "Organization Tree",
            link: "/org/employees/organization-tree",
            permission: "",
            checkable: "permissions",
            parentId: 73,
          },
          {
            id: 733,
            label: "Logins",
            link: "/org/employees/logins",
            permission: "",
            checkable: "permissions",
            parentId: 73,
          },
          {
            id: 734,
            label: "Settings",
            permission: "",
            checkable: "permissions",
            link: "/org/employees/settings",
            parentId: 73,
          },
        ],
        parentId: 70,
      },

      {
        id: 74,
        label: "Org Structure",
        permission: "v_o_stuc",
        checkable: "permissions",
        link: "/org/org-structure/business-units/",
        parentId: 70,
      },
      {
        id: 75,
        label: "Onboarding",
        link: "/org/onboarding",
        permission: "v_onbrd",
        checkable: "permissions",
        parentId: 70,
      },
      {
        id: 76,
        label: "Exits",
        link: "/org/exits",
        permission: "v_exts",
        checkable: "permissions",
        parentId: 70,
      },
      {
        id: 77,
        label: "Expenses & Travel",
        link: "/org/expenses-and-travel/expenses/pending-approvals",
        parentId: 70,
        permission: "v_ex_and_tr",
        checkable: "permissions",
      },
      {
        id: 78,
        label: "Documents",
        link: "/org/documents/letters/offer-letter",
        permission: "v_docs",
        checkable: "permissions",
        parentId: 70,
      },
      {
        id: 79,
        label: "Engage",
        link: "/org/engage",
        parentId: 70,
        permission: "v_eng",
        checkable: "permissions",
      },
      {
        id: 80,
        label: "Assets",
        link: "/org/assets",
        permission: "v_asts",
        checkable: "permissions",
        parentId: 70,
      },
      {
        id: 81,
        label: "Helpdesk",
        link: "/org/helpdesk/summary",
        permission: "v_help",
        checkable: "permissions",
        parentId: 70,
      },
      {
        id: 82,
        label: "Hiring",
        link: "/org/hiring/offers",
        permission: "v_hire",
        checkable: "permissions",
        parentId: 70,
      },
      {
        id: 83,
        label: "Report",
        link: "/org/report",
        permission: "v_rept",
        checkable: "permissions",
        parentId: 70,
      },
    ],
  },
  // {
  //   id: 129,
  //   label: "Performance",
  //   permission: "Performance",
  //   checkable: "module",
  //   icon: "dripicons-trophy",
  //   link: "/performance",
  // },
  // {
  //   id: 130,
  //   label: "Project",
  //   permission: "project",
  //   checkable: "module",
  //   icon: "fas fa-clipboard",
  //   subItems: [
  //     {
  //       id: 131,
  //       label: "Summary",
  //       permission: "",
  //       link: "/project/summary",
  //       checkable: "permissions",
  //       parentId: 130,
  //     },
  //     {
  //       id: 132,
  //       label: "Projects",
  //       permission: "",
  //       link: "/project/projects",
  //       checkable: "permissions",
  //       parentId: 130,
  //     },
  //     {
  //       id: 133,
  //       label: "Clients",
  //       permission: "",
  //       link: "/project/clients",
  //       checkable: "permissions",
  //       parentId: 130,
  //     },
  //     {
  //       id: 134,
  //       label: "Invoicing",
  //       permission: "",
  //       link: "/project/invoicing",
  //       checkable: "permissions",
  //       parentId: 130,
  //     },
  //     {
  //       id: 135,
  //       permission: "",
  //       label: "Reports",
  //       link: "/project/reports",
  //       checkable: "permissions",
  //       parentId: 130,
  //     },
  //     {
  //       id: 136,
  //       label: "Bulk Import",
  //       permission: "",
  //       link: "/project/bulk-import",
  //       checkable: "permissions",
  //       parentId: 130,
  //     },
  //     {
  //       id: 137,
  //       label: "Timesheets",
  //       permission: "",
  //       link: "/project/timesheets",
  //       checkable: "permissions",
  //       parentId: 130,
  //     },
  //     {
  //       id: 138,
  //       label: "Task Repository",
  //       permission: "",
  //       link: "/project/task-repository",
  //       checkable: "permissions",
  //       parentId: 130,
  //     },
  //   ],
  // },
  {
    id: 84,
    label: "Quick Links",
    permission: "quick_links",
    checkable: "module",
    icon: "fas fa-external-link-alt",
    subItems: [
      {
        id: 85,
        label: "Quick Add",
        permission: "qa_v",
        checkable: "permissions",
        link: "/quick-links/employee",
        parentId: 84,
      },
      {
        id: 86,
        label: "Quick Update",
        permission: "qu_v",
        checkable: "permissions",
        link: "/quick-links/employee-update",
        parentId: 84,
      },
      {
        id: 87,
        label: "Employee Separation",
        permission: "es_v",
        checkable: "permissions",
        link: "/quick-links/employee-separation",
        parentId: 84,
      },
      {
        id: 88,
        label: "Reports",
        permission: "qr_v",
        checkable: "permissions",
        link: "/quick-links/reports",
        parentId: 84,
      },
    ],
  },
  {
    id: 128,
    label: "Site Visit",
    permission: "site_visit",
    checkable: "module",
    icon: "bx bx-log-in-circle",
    subItems: [
      {
        id: 184,
        label: "Dashboard",
        permission: "",
        checkable: "permissions",
        link: "/employee-site-visit/dashboard",
        parentId: 128,
      },
      {
        id: 185,
        label: "Site Visit Tracker",
        permission: "",
        checkable: "permissions",
        link: "/employee-site-visit/site-visit-tracker",
        parentId: 128,
      },
      {
        id: 186,
        label: "Report",
        permission: "",
        checkable: "permissions",
        link: "/employee-site-visit/report",
        parentId: 128,
      },
    ],
  },
  {
    id: 139,
    label: "Site Onboarding",
    permission: "site_onboarding",
    checkable: "module",
    icon: "bx bx-sitemap",
    subItems: [
      {
        id: 140,
        label: "Site Onboarding",
        permission: "view_site_onboarding",
        checkable: "permissions",
        link: "/site-onboarding",
        parentId: 139,
      },
      {
        id: 141,
        label: "Operational Readiness",
        permission: "v_or",
        checkable: "permissions",
        link: "/site-onboarding/operational-readiness/global-repo",
        parentId: 139,
      },
      {
        id: 142,
        label: "Site Management",
        permission: "v_sm",
        checkable: "permissions",
        link: "/site-onboarding/site-management",
        parentId: 139,
      },
      {
        id: 143,
        label: "QR Tracker",
        permission: "v_qt",
        checkable: "permissions",
        link: "/site-onboarding/qr-tracker",
        parentId: 139,
      },
      {
        id: 144,
        label: "QR Batch",
        permission: "v_qb",
        checkable: "permissions",
        link: "/site-onboarding/qr-batch",
        parentId: 139,
      },
      {
        id: 145,
        label: "Attendance Tracker",
        permission: "v_at",
        checkable: "permissions",
        link: "/site-onboarding/attend-tracker",
        parentId: 139,
      },
      {
        id: 146,
        label: "Attendance Analysis",
        permission: "v_aa",
        checkable: "permissions",
        link: "/site-onboarding/attendance-analysis-tracker",
        parentId: 139,
      },
      {
        id: 147,
        label: "Consent Tracker",
        permission: "v_ct",
        checkable: "permissions",
        link: "/site-onboarding/consent-tracker",
        parentId: 139,
      },
      {
        id: 148,
        label: "Billing",
        permission: "v_bl",
        checkable: "permissions",
        link: "/site-onboarding/billing",
        parentId: 139,
      },
      {
        id: 149,
        label: "Configuration",
        permission: "v_so_cnf",
        checkable: "permissions",
        link: "/site-onboarding/reports",
        parentId: 139,
      },
    ],
  },
  {
    id: 150,
    label: "Service Help Desk",
    permission: "service_help_desk",
    checkable: "module",
    icon: "fab fa-servicestack",
    subItems: [
      {
        id: 151,
        label: "Ticket Dashboard",
        permission: "permissons",
        checkable: "",
        link: "/service-help-desk/dashboard",
        parentId: 150,
      },
      {
        id: 152,
        label: "Ticket",
        permission: "permissons",
        checkable: "",
        link: "/service-help-desk/tickets",
        parentId: 150,
      },
    ],
  },
  {
    id: 153,
    label: "Time Attend",
    permission: "time_attend",
    checkable: "module",
    icon: "far fa-clock",
    subItems: [
      {
        id: 154,
        label: "Dashboard",
        permission: "",
        checkable: "permissions",
        link: "/time-attend/dashboard",
        parentId: 153,
      },
      {
        id: 155,
        label: "Approvals",
        permission: "",
        checkable: "permissions",
        subItems: [
          {
            id: 156,
            label: "Leave",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/approvals/leave",
            parentId: 155,
          },
          {
            id: 157,
            label: "Attendance",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/approvals/attendance",
            parentId: 155,
          },
          {
            id: 158,
            label: "Overtime",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/approvals/overtime",
            parentId: 155,
          },
        ],
        parentId: 153,
      },
      {
        id: 159,
        label: "Shifts & Holidays",
        permission: "",
        checkable: "permissions",
        subItems: [
          {
            id: 160,
            label: "Shifts",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/shifts-and-holidays/shifts/general",
            parentId: 159,
          },
          {
            id: 161,
            label: "Weekly Offs",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/shifts-and-holidays/weekly-offs/weekly-holiday",
            parentId: 159,
          },
          {
            id: 162,
            label: "Holidays",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/shifts-and-holidays/holiday/holiday-lists",
            parentId: 159,
          },
          {
            id: 163,
            label: "Shift Board",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/shifts-and-holidays/shift-board",
            parentId: 159,
          },
        ],
        parentId: 153,
      },
      {
        id: 164,
        label: "Leave",
        permission: "",
        checkable: "permissions",
        subItems: [
          {
            id: 165,
            label: "Leave Plans",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/leave/leave-plans/standard-leave-plan",
            parentId: 164,
          },
          {
            id: 166,
            label: "Leave Types",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/leave/leave-types",
            parentId: 164,
          },
        ],
        parentId: 153,
      },
      {
        id: 167,
        label: "Attendance Tracking",
        permission: "",
        checkable: "permissions",
        subItems: [
          {
            id: 168,
            label: "Capture Scheme",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/attendance-tracking/capture-scheme/scheme",
            parentId: 167,
          },
          {
            id: 169,
            label: "Tracking Policy",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/attendance-tracking/tracking-policy/policies",
            parentId: 167,
          },
        ],
        parentId: 153,
      },
      {
        id: 170,
        label: "Overtime",
        permission: "",
        checkable: "permissions",
        subItems: [
          {
            id: 171,
            label: "Overtime Policies",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/overtime/policies",
            parentId: 170,
          },
          {
            id: 172,
            label: "Overtime Pay Codes",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/overtime/paycodes",
            parentId: 170,
          },
        ],
        parentId: 153,
      },
      {
        id: 173,
        label: "Employee Assignments",
        permission: "",
        checkable: "permissions",
        subItems: [
          {
            id: 174,
            label: "Shift & WeeklyOff",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/employee-assignments/shiftweekoff",
            parentId: 173,
          },
          {
            id: 175,
            label: "Tracking Policy",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/employee-assignments/trackingpolicy",
            parentId: 173,
          },
          {
            id: 176,
            label: "Overtime Policy",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/employee-assignments/overtimepolicy",
            parentId: 173,
          },
          {
            id: 177,
            label: "Capture Scheme",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/employee-assignments/capturescheme",
            parentId: 173,
          },
        ],
        parentId: 153,
      },
      {
        id: 178,
        label: "Reports",
        permission: "",
        checkable: "permissions",
        link: "/time-attend/reports",
        parentId: 153,
      },
      {
        id: 179,
        label: "Settings",
        permission: "",
        checkable: "permissions",
        subItems: [
          {
            id: 180,
            label: "General",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/settings/general",
            parentId: 179,
          },
          {
            id: 181,
            label: "IP Networks",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/settings/ipnetworks",
            parentId: 179,
          },
          {
            id: 182,
            label: "Geo Location",
            permission: "",
            checkable: "permissions",
            link: "/time-attend/settings/geolocations",
            parentId: 179,
          },
        ],
        parentId: 153,
      },
    ],
  },
  {
    id: 188,
    label: "App Support",
    permission: "group_support",
    checkable: "module",
    icon: "bx bx-support",
    subItems: [
      {
        id: 189,
        label: "Dashboard",
        permission: "v_gs_dash",
        checkable: "permissons",
        link: "/app-support/dashboard",
        parentId: 188,
      },
      {
        id: 190,
        label: "Tickets",
        permission: "v_t",
        checkable: "permissons",
        link: "/app-support/tickets",
        parentId: 188,
      },
    ],
  },
  {
    id: 205,
    label: "Terminal",
    icon: "fas fa-terminal",
    permission: "terminal",
    checkable: "module",
    link: "/log-viewer",
  },
];

//NOTE Last id is 205
